Lesson 10
Ola793/qa-automation pull request #7
Opened 2023-11-16 03:18 UTC by Ola793

2023-11-16 10:58 UTC, Art-auto commented on api_helper/api_helper.js
> +export async function postPosts(url) {
```suggestion
export async function postPosts(url, requestBody) {
```
add body as a parameter

2023-11-16 11:02 UTC, Art-auto commented on async_task.js
> +  )
```suggestion
  return promise
```
перевісти обробку промісу поза тіло функції

2023-11-16 11:03 UTC, Art-auto commented on async_task.js
> +resolveNumber()//далі обробка промісу, в консолі або, наприклад, Resolved 7, або Rejected 2 (в залежності від рандомно створенного числа)
```suggestion
resolveNumber().then(
    resolve => console.log(resolve)
  ).catch(
    reject => console.log(reject)
  )
  //далі обробка промісу, в консолі або, наприклад, Resolved 7, або Rejected 2 (в залежності від рандомно створенного числа)
```

2023-11-16 11:03 UTC, Art-auto requested changes
Внеси зміни відповідно до коментарів

2023-11-16 11:03 UTC, Art-auto commented
Також потрібно вирішити конфлікти

2023-11-17 19:19 UTC, Ola793 commented
Corrected all comments, and resolved all conflicts.

2023-11-19 15:21 UTC, Art-auto approved these changes
All good

2023-11-19 19:07 UTC, merged